/*
 * FolderTree・テストクラス
 * © 2013 Force.com Developer
 * ----------------------------------------
 * @createdDate      : 2013/01/01
 * @createdName      : TAIKI,YOSHIKAWA
 * ----------------------------------------
 * @lastModifiedDate : 2013/01/01
 * @lastModifiedName : TAIKI,YOSHIKAWA
 * ----------------------------------------
 */
@isTest
private class JQueryFolderTreeControllerTest {

	/*
	 * コンストラクタ・テスト
	 */
    static testMethod void JQueryFolderTreeControllerTest() {
        System.debug('◆◆◆◆JQueryFolderTreeControllerTest:START');
        
        JQueryFolderTreeControllerTest cls = new JQueryFolderTreeControllerTest();
		
		System.debug('◆◆◆◆JQueryFolderTreeControllerTest:END');
    }
}