/**
 * フォルダツリー表示
 * © 2013 Force.com Developer
 * ----------------------------------------
 * @createdName      : Taiki,Yoshikawa
 * @lastModifiedName : Taiki,Yoshikawa
 * ----------------------------------------
 */
@isTest
private class JQueryFolderTreeControllerTest {

    /**
     * コンストラクタ
     */
    static testMethod void JQueryFolderTreeControllerTest() {
        
        Test.startTest();
        
        JQueryFolderTreeController cls = new JQueryFolderTreeController();
        
        Test.stopTest();
    }
}