/*
 * FolderTree・コントローラークラス
 * © 2013 Force.com Developer
 * ----------------------------------------
 * @createdDate      : 2013/01/01
 * @createdName      : TAIKI,YOSHIKAWA
 * ----------------------------------------
 * @lastModifiedDate : 2013/01/01
 * @lastModifiedName : TAIKI,YOSHIKAWA
 * ----------------------------------------
 */
public with sharing class JQueryFolderTreeController {
	
	/*
	 * コンストラクタ
	 * @param	: なし
	 * @return	: なし
	 */
	public JQueryFolderTreeController() {
		System.debug('◆◆◆◆JQueryFolderTreeController:START');
		
		System.debug('◆◆◆◆JQueryFolderTreeController:END');
	}
}